### ISSUE TITLE
Installed and activated, error in Media Settings drop-down

### ISSUE THREAD

**Issue by presswizards** [adamsilverstein/modern-images-wp#12]
On /wp-admin/options-media.php when trying to choose an image format for JPGs, it shows the drop-down as:

- Use original format (default)
- There has been a critical error on this website. ...

The email I received details the error:

Error Details
=============
An error of type E_ERROR was caused in line 195 of the file /var/www/vhosts/marlbrough.com/httpdocs/wp-content/plugins/modern-images-wp-main/src/Setting.php. Error message: Uncaught Error: Call to undefined function Modern_Images_WP\str_to_upper() in /var/www/vhosts/marlbrough.com/httpdocs/wp-content/plugins/modern-images-wp-main/src/Setting.php:195
Stack trace:
#0 /var/www/vhosts/marlbrough.com/httpdocs/wp-content/plugins/modern-images-wp-main/src/Setting.php(117): Modern_Images_WP\Setting->isImageFormatSupported()
#1 /var/www/vhosts/marlbrough.com/httpdocs/wp-admin/includes/template.php(1743): Modern_Images_WP\Setting->Modern_Images_WP\{closure}()
#2 /var/www/vhosts/marlbrough.com/httpdocs/wp-admin/includes/template.php(1701): do_settings_fields()
#3 /var/www/vhosts/marlbrough.com/httpdocs/wp-admin/options-media.php(156): do_settings_sections()
#4 {main}
thrown

**Comment by wolffe** [comment]
The actual function should be `strtoupper()` - see here - https://www.php.net/manual/en/function.strtoupper.php

**Comment by adamsilverstein** [comment]
Thanks @presswizards this was fixed in #17 

@wolffe is that using the original image instead of a sub-sized image?

**Comment by wolffe** [comment]
I can't remember, actually, I stopped using it. It _might_ have the been the original image.
