### ISSUE TITLE
Fata error when enabling plugin

### ISSUE THREAD

**Issue by jenxi** [adamsilverstein/modern-images-wp#15]
Wordpress detected a fatal error when I enabled the plugin and went to the settings.

WordPress version 5.8
Current plugin: Modern Images WP (version 1.0.1)
PHP version 7.4.21

```
Error Details
=============
An error of type E_ERROR was caused in line 195 of the file /wp-content/plugins/modern-images-wp/src/Setting.php. Error message: Uncaught Error: Call to undefined function Modern_Images_WP\str_to_upper() in /wp-content/plugins/modern-images-wp/src/Setting.php:195
Stack trace:
#0 /wp-content/plugins/modern-images-wp/src/Setting.php(117): Modern_Images_WP\Setting->isImageFormatSupported()
#1 /wp-admin/includes/template.php(1743): Modern_Images_WP\Setting->Modern_Images_WP\{closure}()
#2 /wp-admin/includes/template.php(1701): do_settings_fields()
#3 /wp-admin/options-media.php(156): do_settings_sections()
#4 {main}
 thrown
```

**Comment by adamsilverstein** [comment]
Thanks for reporting @jenxi - fixed in #17
